### ISSUE TITLE
Remove the cursors(or pointers) on iOS

### ISSUE THREAD

**Issue by litchie** [litchie/exult-ios#1]
There are many different types of pointers, arrows, fingers. I am wondering if we need to keep them on iOS.

**Comment by DominusExult** [comment]
Hmm, I'm wondering about that. Most likely no, we don't need any pointer (except for the "is blocked/can't get there").
I'll play a bit tonight with the computer version and will try to concentrate what I think of that.

**Comment by litchie** [comment]
Yeah, it's a good idea. Make sense to selectively show some of them.

**Comment by DominusExult** [comment]
So, played a little bit last night and the pointers can go. It will be strange to play without them but on a touch interface they make no real sense.

The blocked/can't get there/red cross still need to be shown when needed.

**Comment by DominusExult** [comment]
Combat cursor is still shown. To enter combat mode, doubleclick the avatar and click on the pigeon in the lower left of the paperdoll.

**Comment by litchie** [comment]
yes, I can see that, will get it fixed

**Comment by DominusExult** [comment]
fixed it myself just now b2aebdec28d5d55582c2c4078f58a16d0942ace6
