### ISSUE TITLE
the bundle has *all* the files from the /data source folder

### ISSUE THREAD

**Issue by DominusExult** [litchie/exult-ios#12]
This is a bit over the top, since Exult only needs the flx files.
very minor issue, though :)

**Comment by DominusExult** [comment]
I'm thinking that _maybe_ it would make more sense to add a /data folder in the ios folder, move the binaries and the .h files into that. Then include that in the packaging scheme, instead of the root data folder.
That makes it seem "cleaner" to me, but not sure.

**Comment by litchie** [comment]
That's exactly what I have in mind:)
