### ISSUE TITLE
Replace "Exit" in main menu with link to Exult homepage or forum

### ISSUE THREAD

**Issue by DominusExult** [litchie/exult-ios#14]
Do you think it would be possible to replace the "Exit" in the main menu with "Exult Homepage" or "Help" that will open up safari with our homepage or our forum or our documentation page?
And which of those do you think are more appropriate?

**Comment by litchie** [comment]
I prefer "Help", and it should go to a page that's intended for iOS version, with guide of adding games.

**Comment by DominusExult** [comment]
hmm, that seems like it can be arranged :)
In this case I'd probably add an iOS section to our documentation. It got a Zaurus guide so an iOS guide is no problem. As I'm the one maintaining our documentation... :)

**Comment by DominusExult** [comment]
for now pointing to our documentation at http://exult.sourceforge.net/docs.php should be fine, until there is more to show :)
