### ISSUE TITLE
CoreAudio MIDI?

### ISSUE THREAD

**Issue by DominusExult** [litchie/exult-ios#17]
I was wondering what is up with iOS' CoreAudio Midi. It's disabled for iPhone and even though I messed a bit around I couldn't get it to compile when I enabled it.
I noticed that you disabled CoreAudio in DOSPad so I wanted to ask what the matter is with it? it's not really needed and the FMOpl emu is probably much better in performance and I have no idea what the Midi sounds like on iOS, I just wanted to know :)

**Comment by litchie** [comment]
Last time I checked it's not really supported on iOS, that is why you can't compile it.

**Comment by DominusExult** [comment]
thanks!
