### ISSUE TITLE
non pausing GUMPs still clears GUI movement controls

### ISSUE THREAD

**Issue by andwan0** [litchie/exult-ios#19]
In iPad branch, we have the nice GUI movement buttons (which map to the numpad).

The GUI movement buttons disappear when we open any GUMPS window.
However, in options we can set "game pause when GUMPS open" to be disabled/false.
But GUI movement buttons still disappear when we open any GUMPS window (but game is still running).

**Comment by DominusExult** [comment]
The GUI movement/menu buttons were preventing the use of gumps, for example saving was near impossible. So I disabled them whenever gumps are opened. The "game pauses..." setting needs to be fixed, so the game always pauses when gumps are open. 
For now, while the GUI buttons are the only way to move in the game.
