### ISSUE TITLE
REQUEST: GUI quickkeys & HUD

### ISSUE THREAD

**Issue by andwan0** [litchie/exult-ios#20]
1. HUD, such as compass coordinates, and watch time, and total gold, assuming we have picked up the items to display them. If you used iPad/Android, it's very tedious having to open the character, open bag, then find compass/watch/abacus.
2.  HUD quick buttons to access cheats or bag inventory for each player.

**Comment by DominusExult** [comment]
1. this is not as easy as it sounds :)
   - for time, compass and coordinates you can use the new shortcutbar, double tap on the notebook and the cheatscreen will tell you these.
2. such a hud filled with the many arrow types (plain, magic, sleep, bolts, magic bolts, ammunition for the musket and many more arrow types in SI) and many gold types (gold coins, gold bars, gold nuggets, filari, monetari...) would be way too big.
3. you don't need to know that often how much you really have on you - money a couple of times, but arrows and such, almost never. If the party member have another weapon besides the bow, they will use that when the arrows are gone.
4. The plan is to make the cheatscreen useable
