### ISSUE TITLE
Shortcutbar implementation crashes Exult on loading a savegame

### ISSUE THREAD

**Issue by DominusExult** [litchie/exult-ios#21]
e12c5bc8b84fee473cc8ac3078a8e9568de845ef make Exult crash on loading a savegame.

Steps to reproduce:
- start a game
- save
- load this savegame

Something in the cleaning up of the gump is crashing according to Xcode.

**Comment by DominusExult** [comment]
Tried to debug this more but didn't succeed. Something with the gump is not right and the cleanup fails...

**Comment by litchie** [comment]
This is in fact a regression. Will fix it as soon as possible.

**Comment by DominusExult** [comment]
Heya, thanks for the crash fix, but now the shortcutbar is no longer there on loading a savegame :)

**Comment by litchie** [comment]
Are you sure? I still have it after load a game.

**Comment by litchie** [comment]
If you are still seeing this bug, can you share a saved game file so that I can try to reproduce the problem?

**Comment by DominusExult** [comment]
Actually the shortcut gump does not show at all anymore with this change. Clean build, clean exult.cfg, either starting a new game or loading a savegame.
(btw. you comitted some autotool files (compile, config.guess, missing))

**Comment by DominusExult** [comment]
Just tested it again.
No luck with Xcode 7.0.1 and an iPad on iOS 9.0.2.
No luck with Xcode 7.1 beta 3 and an iPhone 6 on iOS 9.1 beta5.
In both cases the shortcut bar is no shown with these changes :(
