### ISSUE TITLE
Savegame gump and instant name change keyboard popup

### ISSUE THREAD

**Issue by DominusExult** [litchie/exult-ios#22]
When you open the savegame gump and select an existing savegame, instantly the name change iphone keyboard pops up and you need to hit cancel when you just want to load this save.

I have no idea if that can be made to work differently, maybe it can be first selected and _then_ on another click/tap pop up the keyboard.

**Comment by DominusExult** [comment]
looking at https://github.com/litchie/exult-ios/blob/master/gumps/Newfile_gump.cc#L801
it seems to me that if (selected == -2 || selected >= 0) would need to be split and if (selected >= 0) would need an extra rule to only promptForName if there is another click on this field.

**Comment by DominusExult** [comment]
@litchie can you add a special case to ios_utils.mm so that when you call that from https://github.com/litchie/exult-ios/blob/master/gumps/Newfile_gump.cc#L805 it will _select_ the TextField but will only call - (void)promptForName:(NSString*)name when you select it again?

**Comment by litchie** [comment]
Just trying to following up on this issue: is it that the alert dialog shouldn't show immediately?

**Comment by DominusExult** [comment]
is that called "alert dialog"?
What I mean is:
- open the save/load gump
- tap on an existing save
- the iOS name entry dialog and keyboard pop up

But most people will not want to change the name but just want to load an existing savegame - so maybe it (alert/name entry dialog) should pop up on second tap on a savegame.

Also, the alert pops up a second time when you do the above steps,
 then press cancel in the alert dialog,
then press cancel in the Save/load gump.
The alert dialog for that savegame will pop up again.
