### ISSUE TITLE
Quicksave when switching from Exult

### ISSUE THREAD

**Issue by DominusExult** [litchie/exult-ios#26]
I think it might be a good idea to use the quicksave feature when closing/switching from Exult.
When playing it would need to recognize the switch (I think that's possible in SDL) then execute our quicksave action (via keyboard it would be ctrl-s, I can't look at the code right now to look up the function).
When starting Exult again, the quicksave is loaded on "continue onward".

**Comment by litchie** [comment]
Good idea.
