### ISSUE TITLE
Cheat screen - needs text input

### ISSUE THREAD

**Issue by DominusExult** [litchie/exult-ios#28]
The cheatscreen (cheat_screen.cc) needs a text input mode as well.

I'm currently working on cramping the text in the upper half of the screen, so a keyboard will not overlap the text.

It might be nice if the keyboard only comes up when you tap the screen and when you change cheatscreen screens it disappears again until you tap again.

**Comment by DominusExult** [comment]
made the Cheatscreen much leaner with b17da23 - sadly a _lot_ of #ifdef **IPHONEOS**

**Comment by litchie** [comment]
I forget how to enter cheatscreen...

**Comment by DominusExult** [comment]
double click the notebook, the greenish book, in the shortcut bar :)

**Comment by DominusExult** [comment]
Many thanks, it works nicely. Exult is now much more fun with the shortcut bar working quite nicely now.

**Comment by litchie** [comment]
You did a great job cleaning up the cheat screen:-)  

One thing I am wondering is if older iPhones have the hide keyboard button in the virtual keyboard. If not, it could be a problem. Too bad I don't have such a device to confirm.

**Comment by DominusExult** [comment]
Tested with my old iPhone 4 which is on iOS 7 -> unfortunately no hide keyboard button :(
