### ISSUE TITLE
Shortcut bar

### ISSUE THREAD

**Issue by DominusExult** [litchie/exult-ios#3]
I think for a touch interface we need a shortcut bar. Exult is very driven by shortcuts even though most stuff (except for the cheats) can be done by clicking through several stuff.
Need to think about which shortcuts would be best.

**Comment by litchie** [comment]
I am thinking that we can put shortcut buttons at the bottom of screen -- the actual display area doesn't cover full screen.  We can shift it up a little bit to have more room, especially for iPhone.

**Comment by DominusExult** [comment]
What definitely needs to be added are shortcuts to the F2-Cheat menu and the F3 cheat map (when cheats are enabled).
The F2-Cheat menu needs keyboard input as well.

**Comment by DominusExult** [comment]
Thought some more about it and I think this should be done through Exult's gump system. Very similar to the way the facestats (Gameplay Options -> Status Bars) work.
Also using the graphics from the games. Right now I can think of the disk for menu, sword for toggling combat, map, something for target (maybe a bow and arrow target) and definitely a spellbook, maybe the keyring in Serpent Isle.
For cheating, I'm thinking of maybe using double-clicks/taps on disk for the f2 menu, map for teleporter, target for teleport target.
I may be able to do this, maybe it's over my head ;)

**Comment by DominusExult** [comment]
I may be too advanced for me. For keeping a record of what I tinkered already a bit:
- Settings 
          Gumps.vga shape 24, frame 0
          in SI shape 19 but it should work as been done in misc_buttons.cc
          (Gamemenu_gump *menu = new Gamemenu_gump(); see misc_buttons.cc)
          (doubleclick cheat.cheat_screen();)
- Toogle combat/peace 
          Gumps.vga, shape 46, frame 0 peace, frame 1 combat
          in SI shape 41 but should also be doable as in misc_buttons.cc
          (gwin->toggle_combat(); see misc_buttons.cc )
- Map
          shapes.vga, shape 178, frame 0
          (doubelclick cheat.map_teleport(); )
          _needs check whether a map is in inventory_
- Spellbook
          shapes.vga, shape 761, frame 0
          _needs check whether a spellbook is in inventory_
- Backpack  
          shapes.vga, shape 801, frame 0
- Key
          shapes.vga, shape 641, frame 2 (or frame 28)
          in SI Keyring
              shapes.vga, shape 485, frame 0
          _In SI needs check whether a keyring is in inventory_
- Notebook
          shapes.vga, shape 642, frame 7
- Target 
          pointers.vga, shape 0, frame 2
          (see ActionTarget in keyactions.cc)
          (doubleclick cheat.cursor_teleport();)
- Jawbone (SI only)
          shapes.vga, shape 555, frame 0 or 18 (all teeth)

**Comment by DominusExult** [comment]
I made a little patch that modifies the face stats (gameplay options -> status bar -> middle) to show the disk and combat icon instead of the faces. Singleclick on the disk opens the in game menu, doubleclick on the combat icon will toggle combat (without adding a ton of SDL event stuff to differ between single and doubleclick, I wasn't able to assign both single and doubleclick events and for some reason the combat toggle only sticks on doubleclick).
This is just some kind of prove of concept, I don't think I can proceed from this point. I'm just not good enough to make a totally new gump for this. I hit too many problems that my limited coding knowledge can't cope with :)
Also I wonder if in a gump you can assign a color to be transparent. Obviously the icons need to have their brown made transparent.
![exulttoolbar](https://cloud.githubusercontent.com/assets/3313896/7737801/6257b1c4-ff4e-11e4-9dc8-73472043c159.png)

Patch on Pastebin http://pastebin.com/Rf6EXiyT

**Comment by litchie** [comment]
A good start.  Now only thing to do is to put them in a new gump. For the combat button, I think we should avoid double click if possible.

**Comment by litchie** [comment]
@DominusExult  You gave a long list above, I am wondering what exactly we need to put on the shortcut bar, because we have limited screen estate, especially on iPhone.  Will try to implement in the next two days.

**Comment by DominusExult** [comment]
8 shortcuts should work fine, it does for the party faces in the status bar. All 9 should probably work as well. I added some additional notes in the list above about what needs to be checked and when to display some shortcuts (the gameplay shouldn't have all available right away - spellbook for example requires you to have one - in SI it takes a while before you have one).

Another thing to pay attention to is the status bar, which is always on the bottom.
Maybe make it available on top as well and make sure that depending where the shortcut bar is (top or bottom) the status bar is on the opposite.

If the brown of combat/peace button can't be declared transparent, I'll make new shapes. I'll be gone for about two weeks now, though. I can see the changes and make comments but won't be able to compile/test during that time.

**Comment by litchie** [comment]
Where did you find those shape numbers and frame numbers? I am having trouble loading the shapes.

**Comment by DominusExult** [comment]
I found those with Exult Studio. But you can see a way of loading them in gumps/misc_buttons.cc/h

**Comment by litchie** [comment]
Thanks. Much better than magic numbers!

**Comment by DominusExult** [comment]
(And make sure it's the right vga file ;))

**Comment by DominusExult** [comment]
Another was to browse the shapes is with the in game shape browser (ctrl-b and cheats enabled). But you need to run the desktop version ;)

**Comment by litchie** [comment]
Just found that shapes painting behaves not as I assumed.  Its painting area can extend to the left of the origin point, which is quite different from image drawing we see elsewhere.  It's not that I couldn't load those shapes, they were just drawn outside window area!

**Comment by DominusExult** [comment]
Ouch! Frustrating

**Comment by litchie** [comment]
There are still things to do:
1. fix transparency
2. align the shapes better
3. fill in missing action code
4. show cheat buttons only when cheat is enabled?

![1](https://cloud.githubusercontent.com/assets/1026634/8148819/556fac1e-12e0-11e5-97e1-5625b8a4bf9d.png)

**Comment by DominusExult** [comment]
1. I think it _might_ be possible to assign a color to transparency for the gump only.
   Otherwise, and looking at the other buttons, I'll make a transparent disk, peace/combat icon AND MAKE bigger shapes for the other buttons (seems like 1.5x scale for those). Then add them to the iphone.flx.
2. none of the buttons are cheat only, just some of the actions are (cheat map, cheat screen). The spellbook (both BG and SI) and in SI the keyring and jawbone should be dependent wether the items are in the party inventory. There is existing code that checks this, probably in the keyboard shortcuts.

Thanks for adding this. Looks great!

**Comment by DominusExult** [comment]
2 should be concerning 4. Github auto "corrected" this

**Comment by litchie** [comment]
It would be great if you can make custom shapes for those buttons. Currently they are inconsistent in style and size :-)

**Comment by DominusExult** [comment]
Ha, I wish I was a pixel artist - I can only hope to make them bigger and not have it look worse ;)

**Comment by DominusExult** [comment]
had sometime to look at it finally.
Some issues (apart from having to do some pixel art somehow :)):
- maybe doubleclick is not the right way to access secondary functions of the buttons. The way doubleclick is recognized by first doing the singleclick option might be problemtatic. Maybe a tap+hold for some seconds? is that feasible?
  as per https://developer.apple.com/library/ios/documentation/EventHandling/Conceptual/EventHandlingiPhoneOS/GestureRecognizer_basics/GestureRecognizer_basics.html "LongPress" could be added, I think.
- The bar is fixed on the blackness above the game window. I think it should be more flexible (like the status bars). Especially since on the iphone the aspect is all wrong by default and when you turn on aspect correction the black border is gone.
- the combat button is not tracking the state of combat by toggling between frame 0 and 1 (as does the misc_buttons) <- that's kind of important since it's the only way to know whether you are in combat (as we did away with the mouse arrow that changed to red in combat mode).

I hope to have time to do some art stuff later this week and maybe add some SI cases and some functions to the buttons.

**Comment by litchie** [comment]
If we are to implement the shortcut bar as a standard iOS control floating on top, we can use all kinds of gesture recognizers for free.  Doing gesture recognition with plain SDL API is painful if not impossible. If we need to keep the shortcut bar as a gump, then I think perhaps we can run iOS gesture recognizer directly on SDL Window, and translate the results (and coordinates) to the shortcut bar gump. 

Will check the aspect correction and make sure it is always inside screen.

Will check combat mode.

**Comment by DominusExult** [comment]
I _think_ keeping it as a gump is better because this way the buttons get scaled alongside the game window, depending on the scaler that is set in the graphics options.
Perhaps the doubleclick needs to be detected the painful way that Exult uses generally for detecting a doubleclick (for example clicking on the avatar vs doubleclicking) instead of the iOS way you are using AFAICT. (for example the status bar gump checks for doubleclick as well. see gumps/face_stats.cc/.h)

**Comment by DominusExult** [comment]
added some button actions and added some comments. Is it possible to reuse the ActionFuncs from keyactions.cc? A lot of those would be nice to just be able to reference the function instead of rewriting it.

The doubleclick actions are a bit hit and miss :)

**Comment by DominusExult** [comment]
Some buttons should only show when the corresponding item is in the party inventory. For this I added the "is_party_item" function in 7d976089a648e64408651f9e0b316cb097c6c713
Is it possible to leave blend out buttons in the middle of the bar (for example the spellbook)? I have no clue how to go about this because of the enumeration.
Related to this, can the gump "update" when it finds the items in the inventory? I have no idea if this is possible as it sounds as if it would need to poll the inventory then in certain intervals or always check for these items when the party adds an item. On save/reload the gump probably updates, couldn't check due to the savegame load crash.

I've got two savegames of Serpent Isle for this:
https://www.dropbox.com/s/br1vcfxikgfklog/exult01si.sav?dl=0 which has spellbook, keyring, jawbone in front of the avatar, for easy adding to the inventory
https://www.dropbox.com/s/id7gyvxkt3dws6n/exult02si.sav?dl=0 has them already added

**Comment by litchie** [comment]
> Is it possible to leave blend out buttons in the middle of the bar (for example the spellbook)?

Do you want to hide it temporarily while keeping its place or do you want to remove it totally from the bar?  I guess we will need to add a flag to the BarButtonItem struct, such as:

```
   bool hidden;
```

Before drawing, we can check inventory and update hidden flag accordingly. So when we are drawing the bar buttons, we will skip those hidden=true items.

**Comment by DominusExult** [comment]
Hmm, removing it and having the next button take its place would perhaps look cleaner.

But another idea is to have a "greyed out" icon for those buttons that are not available yet.

What do you think? 4 possibilities:
- show the button and just not have it working
- show a greyed out button and not have it working
- hide the button
- remove the button and have the next working button shown

**Comment by litchie** [comment]
I prefer a greyed out button when the button is not working. The problem is that there don't seem to be a ready-to-use shape drawing function that can draw the same shape with different transparency.

**Comment by DominusExult** [comment]
Then  greyed out it is ;)
And I'll make a greyed out button for those. Should be doable.
I _have_ to do some buttons for sure.

For example the keyring in SI doesn't look bad in the bar, but it has some color cycling, making a key appear to glow, which is too distracting in the bar.
The combat/peace brown background issue can be solved by copying the shapes from SI because in that game they already have a transparent background ;)
When I have better buttons I'll add them to the iphone flx file.

**Comment by litchie** [comment]
Great. You may need to cache inactive state shape in the BarButtonItem, along side with the normal state shape we already have.

**Comment by DominusExult** [comment]
All buttons work now.
Overall the shortcut bar seems a bit unstable. Especially the buttons that call the green crosshair (key, keyring, lockpick, target, feed) seem at times disruptive. Can't quite reproduce always.

I've added the notebook and the cheat screen (doubleclick notebook) as well, but both need a keyboard.

**Comment by litchie** [comment]
The handling of double click on notebook is problematic. I think we should keep just one function for most buttons, at least before we can implement the double click correctly. For now, please put a guard around the handling code in onItemClicked:

```
   if (!doubleClicked) {
          // Handling event
  }
```

Btw: Do we really need the cheat screen? Can't cheats be made by editing a config file?  Bringing up a soft keyboard will always cover at least half of the screen.

**Comment by litchie** [comment]
Just did a build, nice to see buttons in action!

Like I commented above, some of the buttons may not function correctly because we try to do two things for a button.   In current implementation, a double click will first trigger a single click event, then a double click event.  I'll try to find a fix, for now, please assign only one function to one item.

**Comment by DominusExult** [comment]
Unfortunately cheats only work through keyboard shortcuts or the cheat screen.
Two things I'm considering:
- adding a settings gump for toggle cheats (god mode, archwizard, intravision, hackmover etc.)
- making a special iphone version of the cheat screen that only uses half the screen. Not every cheat needs to be in the ios version (those that change schedules) but things like teleport to npc or to coordinates are great for debugging while mobile.

It would be really great to have some way to trigger a secondary function of the shortcut bar buttons. Especially for map teleport cheat or teleport to cursor.
Which reminds me that I need to limit those functions to when cheating is globally enabled.

I've also spent some time on button icons and will try to test them next to have a slightly better look.

**Comment by DominusExult** [comment]
I've tried my best on the icons but unless I doubled their size, which is too big, I wasn't successful with good looking ones. Needs a better pixel artist :(
I'll do the  if (!doubleClicked) changes next time.

I made some greyed out shapes for the spellbook and jawbone but I have no idea how to go about

> Great. You may need to cache inactive state shape in the BarButtonItem, along side with the normal state shape we already have.

**Comment by litchie** [comment]
Just give me the shape numbers, I'll do the state change code.

**Comment by DominusExult** [comment]
Thanks!
The BG Spellbook is ShapeID(6, 0, SF_IPHONE_FLX), the greyed out one ShapeID(6, 1, SF_IPHONE_FLX). The SI spellbook is ShapeID(6, 2, SF_IPHONE_FLX), greyed out ShapeID(6, 3, SF_IPHONE_FLX). See gumps/iphone_gumps.cc:115 and following.

The Jawbone (SI only - if you haven't played through SI yet, it's a teleportation device) is ShapeID(4, 0, SF_IPHONE_FLX), greyed out ShapeID(4, 1, SF_IPHONE_FLX). See gumps/iphone_gumps.cc:166.

Another, similar case is the SI keyring. In BG you just have all the keys in your backpack, in SI you can get a keyring, a container for all your keys. But you don't have it right away, so the key button should change to the keyring shape once you have it. See gumps/iphone_gumps.cc:135...
Keyring is ShapeID(5, 0, SF_IPHONE_FLX) and the normal key is ShapeID(641, 28, SF_SHAPES_VGA).

**Comment by DominusExult** [comment]
Hmm, spent some more time looking at the shortcut bar code.
I _think_ it needs to be more similar to the face_stats.cc/.h, registering the buttons as Gump_button and then being able to use on_button for single click and double_clicked for the double click.

Also reusing the autorefresh of the face_stats would help as well. I've dabbled a bit in the position of the bar to make it auto align with the top, regardless of resolution and aspect correction state.
Currently I have this:
void ShortcutBar_gump::createButtons()
{
    int x = 0;
    int starty = gwin->get_win()->get_start_y();
    int endy = gwin->get_win()->get_end_y();
    int resy = gwin->get_win()->get_full_height();
    int gamey = gwin->get_game_height();
    y = 20+starty;
....
....  
    buttonItems[i].rect = new Rectangle(x, y, barItemWidth, height);

But I need to look again as I didn't realize it wouldn't auto align unless I restarted Exult, so with these ints above it might be, should be, possible to come to an auto alignment, I hope.

**Comment by litchie** [comment]
I don't have access to the dev machine right now, but there is one quick thing you can check: double click on the Face_stats button, and see if the on_button is called at all (by adding a printf statement inside that function). If no, then we can copy what they did; if yes, then it's exactly the same behavior as our current implementation.

**Comment by DominusExult** [comment]
I'll do the tests tonight (GMT) but just by observing it seems the single click doesn't get used when you doubleclick.
On single click on a face in the face stats the name of the party member willbe written above the party member.
When you doubleclick the inventory of the party member opens without the name being written.

**Comment by DominusExult** [comment]
apologies, the result of the printf is that it does indeed register a single click on the face as well.
But I don't understand what happens next since the doubleclick on the face buttons works so much better than the shortcut gump ones...

**Comment by DominusExult** [comment]
More investigation:
The way Exult differs between single and double clicks is different and "works" better because it filters out single clicks when it is actually a double click. That's why you see a short delay when you click on a face in the face status bar.
SDL's event->button.clicks function doesn't do that, mainly because it will always add a delay when you try to differ.

So, to make the shortcut bar better in this regard we will eventually need to filter out single clicks when we mean double clicks.

I tried my best and am not fully successful.
I replaced the code at https://github.com/litchie/exult-ios/blob/master/gumps/iphone_gumps.cc#L309

```
if (event->button.clicks >= 2) {
        onItemClicked(i, true);
    } else {
        onItemClicked(i, false);
    }
```

with

```
Uint32 timeout = 0; //at the beginning of the function
...
timeout = SDL_GetTicks() + 500;
        while (!SDL_TICKS_PASSED(SDL_GetTicks(), timeout)) {
            if (event->button.button == 1) {
                onItemClicked(i, true);
            } else {
                onItemClicked(i, false);
            }
        }
```

I experimented with the if (event->button.button == 1) , changing it to if (event->button.clicks == 1) or if (event->button.clicks >= 2) or if (event->type == SDL_MOUSEBUTTONUP) or if (event->type == SDL_MOUSEBUTTONDOWN)... Always resulting in it reporting many more clicks than a single one, with some only recognizing a single click or only a double click... I think I am on the right track BUT something is obviously missing from my idea to make it work...
Do you see what I'm doing wrong?

**Comment by litchie** [comment]
You are seeing more clicks because that's the way SDL double click works: 

```
 CLICK(event->buttonclicks=1) CLICK(event->buttonclicks=2) 
```

I did a fix on this issue: f28a2f4

**Comment by DominusExult** [comment]
Whoa! Thanks a lot. WAY more complicated than I thought.
I'll clean up this issue and will file seperate issues for the remaining "problems" (combat button updates, button updates when buttons come available or not)

**Comment by DominusExult** [comment]
Split the remaining issues with the shortcut bar in separate items and closing this one for better overview.
