### ISSUE TITLE
so far so good

### ISSUE THREAD

**Issue by DominusExult** [litchie/exult-ios#4]
Thanks a lot. It's working already and I had some fun messing with things.
Do you want to "hear" all the issues? :)
- the menu button is dead after first use
- the dpad works only for a couple of steps and stalls until you touch it again
- on iPhone 5s (ios 8.1.2) the keyboard did not come up when starting a new game of Serpent Isle. It seems as if the keyboard popup hangs - but looking at the code changes, I see you have not done the same changes to gamemgr/sigame.cc as you've done to gamemgr/bggame.cc :)
- we need the data folder in the itunes file sharing as well, to throw in the music/sfx files and the mt32 roms :)
- changing anything in the resolutions loses dpad and menu. But it was interesting to see how high the resolution can go with xbr4 on an ipad (3rd gen). Unplayable but looking great :)
- I think that's code from the previous ios porting, but when you single click anything some kind of menu pops up. I think that's rather annoying :)

Nice work, enjoyed running it!

**Comment by DominusExult** [comment]
one more
- when Exult exits it should probably really exit. For example, when there are no game files it should exit when you click on that notice. Also when you decide to quit the game.

**Comment by DominusExult** [comment]
And sorry, I know, work in progress. I just find it best to write these things down...

**Comment by litchie** [comment]
Great summary. I think it's better to create a separate issue for each of them (important ones).

iOS apps can't quit:-)

**Comment by DominusExult** [comment]
made seperate issues now :)
