### ISSUE TITLE
Wizard Eye spell not "moveable"

### ISSUE THREAD

**Issue by DominusExult** [litchie/exult-ios#43]
When you cast Wizard Eye, you should be able to use the spell view like you normally use the Avatar. But it is not reacting to the d-pad.

**Comment by DominusExult** [comment]
I'm failing at this. The problem is that the Wizard Eye spell is not handling keyboard input, just Mousemotion and I can't adapt the current code to use the dpad for that.
@litchie can you take a look?

To test: download this savegame, unzip, put it into save/blackgate, start Blackgate, start a game, load this savegame ("wizard eye"), tap the spell book in the shortcut bar (black book in the middle) -> spellbook gump opens and the wizard eye spell is selected, doubletap that.
Now the screen should change to a circle with black/grayness around. To move you would need to use the dpad.

The culprit starts in exult.cc:2119, the functions Shift_wizards_eye and the following Wizard_eye

[exult61bg.sav.zip](https://github.com/litchie/exult-ios/files/443167/exult61bg.sav.zip)

**Comment by litchie** [comment]
I haven't run the game yet.  I am thinking that if dpad is used for moving around, can we also use it for shifting wizard eye? Can't we use touch events?

**Comment by DominusExult** [comment]
yes, using the dpad would probably be easiest, moving it around with the finger would be great, too.

I couldn't adapt the existing code for moving the avatar via the dpad, as that is using joystick movement to mimic keyboard events. But the wizard eye spell is only controllable via mouse.
