### ISSUE TITLE
Exult build fails with header file not found

### ISSUE THREAD

**Issue by Cross22** [litchie/exult-ios#49]
Building with XCode Version 9.0 (9A235)

Error message:
msgfile.cc:34:10: 'ios_state.hpp' file not found

**Comment by Cross22** [comment]
expack & exult projects need to have the "/headers" directory added to their Header Search Paths to resolve this.

**Comment by DominusExult** [comment]
Thanks, I'll look into it this weekend. I might have added the headers with the absolute path since I didn't notice a problem.

**Comment by DominusExult** [comment]
two headers were hardcoded by accident. Should work now (did for me in a different folder).
Thanks again for noticing and reporting this!
