### ISSUE TITLE
Remove single click pop up

### ISSUE THREAD

**Issue by DominusExult** [litchie/exult-ios#6]
I think that's code from the previous ios porting, but when you single click anything some kind of menu pops up. I think that's rather annoying :)

But it could make sense on the smaller idevices screens. No idea how feasible it is to implement this only for smaller devices.

Definitely needs to go away on ipad size.

![singleclick](https://cloud.githubusercontent.com/assets/3313896/5889122/1eb28f1a-a419-11e4-9e48-ad6067392261.png)

**Comment by litchie** [comment]
Aren't these action items necessary?

**Comment by DominusExult** [comment]
You can do everything with the finger action.
It's only useful for small displays, so it might be good to keep it as an option.
Another problem is that these click options need to check whether they are visible on screen which they presently don't.
