### ISSUE TITLE
Changing video options kills the dpad and menu button

### ISSUE THREAD

**Issue by DominusExult** [litchie/exult-ios#7]
changing anything in the resolutions loses dpad and menu.

**Comment by litchie** [comment]
Where did you change the resolution?

**Comment by DominusExult** [comment]
During gameplay, press your menu button, then press "graphics options".

**Comment by andwan0** [comment]
I play between 320x200 (zoomed so I can see those small items/rings) ... and 640x480 so I can see the map better.
Yes, changing resolutions kills the dpad & menu button... which means I have to forceibly kill the app & restart.

**Comment by DominusExult** [comment]
I've traced this back to 
https://github.com/litchie/exult-ios/blob/master/gamewin.cc#L920

```
win->resized(neww, newh, newfs, newgw, newgh, newsc, newsclr, newfill, newfillsclr);
```

commenting that makes video changes not kill the touchUI - of course then every video change is not taking until you restart :)
This is as far as I can debug it :(

Quickest way to test is:
- start a game
- hit esc
- hit Video Options
- hit **Apply**

**Comment by DominusExult** [comment]
with breakpoints set in xcode the point when it goes bad, the TouchUI disappears, is at https://github.com/litchie/exult-ios/blob/master/imagewin/imagewin.cc#L1023

**Comment by DominusExult** [comment]
when I comment the condition
´´´
if (dpad == nil) {
´´´
in - (void)showGameControls of ios_utils.mm the TouchUI will reappear when I close the settings gump, Of course this is no solution as it will put layers upon layers on the TouchUI :)
But it may point you where the problem is...

**Comment by DominusExult** [comment]
awesome! many thanks!

**Comment by litchie** [comment]
My problem is that screen will shrink by half to the center after resolution change, which makes touch very difficult. I don't know if that's ok.

**Comment by DominusExult** [comment]
That should only happen if you set scaler to 1 and fill mode to center.
With which graphics options does that happen to you?
(Also a big problem is that the "touch zone" isn't alligned with the shortcut button on other resolutions than the default one)

**Comment by litchie** [comment]
Yes, I guess it's exactly what I did. I am wondering what's your settings?

![video options](https://dl.dropboxusercontent.com/u/18357422/exult/20151128-resolution-change-opt.png)

![The display](https://dl.dropboxusercontent.com/u/18357422/exult/20151128-resolution-change.png)

**Comment by DominusExult** [comment]
To debug the varios shortcut bar things?
Change back to "scaling 2" but enable "aspect correction" to see how it doesn't apply the changes to the shortcutbar rendering until you restart exult.
Or give Exult a bigger resolution and set game area to auto to experience the problem of click area no longer alligning with the shortcutbar button.

**Comment by DominusExult** [comment]
My recent commits broke this again. Will see what I broke tomorrow. Sorry
